import fs from "node:fs/promises";
import path from "node:path";
import { z } from "zod";
import { SYSTEM_PROMPT } from "@/lib/ai/prompt";
import type { ClassifyThreadInput } from "@/lib/ai/types";
import { classificationResultSchema } from "@/lib/schemas/classification";
import { persistClassification } from "./persistClassification";

const BATCH_DIR = path.join(process.cwd(), "data", "classification-batches");

const INSTRUCTIONS =
  "This batch was generated by a scan run with LLM_PROVIDER=manual (no Anthropic API key used/billed). " +
  "For each entry in `threads`, read `subject`, `storedSummary`, and `newMessages`, then decide the " +
  "classification per `systemPrompt` above. Set that entry's `result` field to a JSON object matching " +
  "exactly this shape: { actionable, reason, summary, priority, tasks: [...], needsReply, suggestedReply, " +
  "confidence } — see systemPrompt for the full field rules. Leave `result` as null on any entry you want to " +
  "skip (it will be left unclassified and can be picked up again on a later scan). When every entry you " +
  "want classified has a filled-in `result`, save this file and run: " +
  "npx tsx scripts/apply-classifications.ts <path-to-this-file>";

const manualBatchThreadSchema = z.object({
  emailThreadId: z.string(),
  accountLabel: z.string(),
  subject: z.string(),
  storedSummary: z.string().nullable(),
  newMessages: z.array(
    z.object({
      fromAddress: z.string(),
      sentAt: z.string(),
      isFromOrgAccount: z.boolean(),
      sanitizedBodyText: z.string(),
    }),
  ),
  // Deliberately unvalidated at this layer: a human/Claude Code session may
  // fill this in with something malformed, and applyClassificationBatch()
  // must be able to read the file anyway to report that as an "invalid"
  // entry rather than fail to parse the whole batch.
  result: z.unknown().nullable(),
});

const manualBatchFileSchema = z.object({
  scanRunId: z.string(),
  createdAt: z.string(),
  instructions: z.string(),
  systemPrompt: z.string(),
  threads: z.array(manualBatchThreadSchema),
});

export type ManualBatchFile = z.infer<typeof manualBatchFileSchema>;

/**
 * Writes one scan run's candidate threads to a JSON file for a human (via a
 * Claude Code session, using an existing Claude subscription instead of a
 * paid Anthropic API key) to classify by hand. The file round-trips: the
 * same shape is read back by applyClassificationBatch() once `result`
 * fields have been filled in.
 */
export async function writeClassificationBatch(
  scanRunId: string,
  threads: { emailThreadId: string; context: ClassifyThreadInput }[],
): Promise<string> {
  await fs.mkdir(BATCH_DIR, { recursive: true });
  const filePath = path.join(BATCH_DIR, `${scanRunId}.json`);

  const file: ManualBatchFile = {
    scanRunId,
    createdAt: new Date().toISOString(),
    instructions: INSTRUCTIONS,
    systemPrompt: SYSTEM_PROMPT,
    threads: threads.map(({ emailThreadId, context }) => ({
      emailThreadId,
      accountLabel: context.accountLabel,
      subject: context.subject,
      storedSummary: context.storedSummary,
      newMessages: context.newMessages,
      result: null,
    })),
  };

  await fs.writeFile(filePath, JSON.stringify(file, null, 2), "utf-8");
  return filePath;
}

export async function readClassificationBatch(filePath: string): Promise<ManualBatchFile> {
  const raw = JSON.parse(await fs.readFile(filePath, "utf-8"));
  return manualBatchFileSchema.parse(raw);
}

export type ApplyClassificationBatchResult = {
  scanRunId: string;
  tasksCreated: number;
  tasksUpdated: number;
  skipped: number;
  invalid: number;
  invalidThreadIds: string[];
};

/**
 * Reads a filled-in batch file and persists each entry that has a `result`,
 * via the same persistClassification() the live orchestrator uses — so
 * manual classifications follow the exact same "never reopen a closed task"
 * and dedup rules as the automated path.
 */
export async function applyClassificationBatch(filePath: string): Promise<ApplyClassificationBatchResult> {
  const batch = await readClassificationBatch(filePath);

  let tasksCreated = 0;
  let tasksUpdated = 0;
  let skipped = 0;
  let invalid = 0;
  const invalidThreadIds: string[] = [];

  for (const entry of batch.threads) {
    if (entry.result === null) {
      skipped++;
      continue;
    }

    const parsed = classificationResultSchema.safeParse(entry.result);
    if (!parsed.success) {
      invalid++;
      invalidThreadIds.push(entry.emailThreadId);
      continue;
    }

    const persisted = await persistClassification({ emailThreadId: entry.emailThreadId, classification: parsed.data });
    tasksCreated += persisted.tasksCreated;
    tasksUpdated += persisted.tasksUpdated;
  }

  return { scanRunId: batch.scanRunId, tasksCreated, tasksUpdated, skipped, invalid, invalidThreadIds };
}
